language: python

addons:
  chrome: stable

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.7
      env: TOXENV=linting
    - python: 3.7
      env: TOXENV=formatting
    - python: 3.7
      env: TOXENV=docs


before_install:
    - wget https://chromedriver.storage.googleapis.com/$(wget https://chromedriver.storage.googleapis.com/LATEST_RELEASE -q -O -)/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - export PATH=$PATH:$PWD

install:
    - pip install tox

script:
    - tox

deploy:
  - provider: pypi
    distributions: bdist_wheel sdist
    skip_existing: true
    user: statoil-travis
    password:
      secure: hnOLsz/JpdeCKYGjw2msTPAQe6W5k9Maner4HySo6HYoWbYqYtkWcboo9f69Mfi7YSAdq+zdeOmwOSLEmcN9Fkh/RxVce+9vkvDmCv+EFmQrilQIwkYA7YTA2T9ylV/b/zknhnX86ucr9+zBM3J9Gb3w0AbdG3/MxXmDpWFJ0Vg9HZWGnevY17j4JxwGSSIhRstJFHzbnYCpYK4+t4p8lOUUIEl7TgU2GWltIRGoc8Ir7obDEkzTsFfF7kfntI7gdGBqpwcQWfApUEl9DoVdtSIRExh2TMzVfVrBzQ+YNvNBqdzW5/AjbrYcP/EYGPnET/zOS0z8hruJ0nxKMz6dtiXbAbqrPppx1WfwQQHakvo+SB4HZ9RXDizA2WWR9gY01n47UF7JCojEgqO0Rfl6hkzHl1V06j+e+WarYB70p/aIz3VEFyEGju/3TNqhxRXvVJUTFllUYcfP0bjoQNVs9iPPNwO4yZwv9oV004uFKD2DeeaGI11cu8cZH+HLMD/j8v3FfqO9G5t+U4aFKLJOw9nPjU7cnV1VLWo5w45k5rGHos4EteaJqYeWAHzAHx3CVsNkdaJnuntjh1SNCrtIf3rLvzVBAqyE/3em4+NxIi7MnRMDNGH8wx+5rITDN/ZturXPSjQIeFMd/+AAfwzlk/7/xU5zOh5YYELSfmRyR6Y=
    on:
      tags: true
      branch: master
