language: python

addons:
  chrome: stable

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.7
      env: TOXENV=linting
    - python: 3.7
      env: TOXENV=formatting
    - python: 3.7
      env: TOXENV=docs


before_install:
    - wget https://chromedriver.storage.googleapis.com/$(wget https://chromedriver.storage.googleapis.com/LATEST_RELEASE -q -O -)/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - export PATH=$PATH:$PWD

install:
    - pip install tox

script:
    - tox

deploy:
  - provider: pypi
    distributions: bdist_wheel sdist
    skip_existing: true
    user: statoil-travis
    password:
      secure: "Fs8EfJFR/kYDcXln1NFVX6SwkKeTHQyz15GUYDqZvkpvFizzGVHrILlGQ/610oOkZ85TP13DCUS+fo/lBjfzvvFI8d1f+5gUHG+OpifvSeUJuZTs8IZZD13dt1a4RKzjP/xFTCU8TTGJKU6iKdXNIvjF3PUQ1OqO4v01E1cMSer3aNd4SimYklxG8HQkucjNI1hQFRO0ORZnI8khXjXVhxWBMwVofGAcwjt9C0dJeSjJQWV+iksfGz6veZwXJJZ/4w0L/J6BPbt06gGWz6SAvba1xQCabvhbZOnybJFUnlzGzsTGmGg0FpWIZJzd07i8iTaZA7oo0bstaHqUeRqUwDwt/59vj3+YRGEgkfVEz0ztqsd+5r5Y6yL2hpBlb9CVhjSLACEM+23bam84bq/iy5eHvjflQDtj409YYXw7lfDixp5XWBhwxEakmHctpa9Pq+1aAFtqFd5nBw6vSjQWZYEe2dHEUYzRBdVuN3ftkp1Q7b4hgc0gfTA8t8MrmY1bjBdKNas8FdwSSSuFjo63CQC/VC1VP7l45M6/4tZveRz60jopdBhXub9hRcG7MjX4FJrJVFFLJLMbpohHoKLocZLOIMjysIJi3sFiBnjCrHWSw6fDi08pm02trAKMucfDuAAZ4wNdl1hRc30mAKgGw4rPbG9U7nDAHjXmbsBKIZI="
    on:
      tags: true
      branch: master
