language: python

addons:
  chrome: stable

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.7
      env: TOXENV=linting
    - python: 3.7
      env: TOXENV=formatting
    - python: 3.7
      env: TOXENV=docs


before_install:
    - wget https://chromedriver.storage.googleapis.com/$(wget https://chromedriver.storage.googleapis.com/LATEST_RELEASE -q -O -)/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - export PATH=$PATH:$PWD

install:
    - pip install tox

script:
    - tox

deploy:
  - provider: pypi
    distributions: bdist_wheel sdist
    skip_existing: true
    user: statoil-travis
    password:
      secure: iVG8sYuzs4pMc1XbinesoJ+mIge3cRIQAbOa4G/a5G/yTJsVLavRxrj+RPz6eOxMVEbMLo55HbIZiQzm/eQqVuOTLUzvPYVkrBEZtDEDLtRC/KYlyzcDwbGlAfe9Dk+fAI6a+GApR2OTV6eHVml5n+dg7tw+jq2BCVuWTdLbFQs7MWp9gf+jOOyIkN85SMyAbvbza4fXk5TzS2VH2Dna3/f0zPDAPXEcFQUCf2qDCDbDk03lfTuinp79fMcbMiuHj6Y4S2e/GgcP+gr7j24vX4GJpsHrMZlTxCPqmpBtggQHN6/V+Y8AKLJUWDJCNdJ5F7YENc8GtVyrQ/F8TLJxWYyN8QUuIegqecyAGdOZWGiNTai4EdmhuK1xlynQ1yBFEQoTM+wjY/zMhBk4Y8J+1TXs1bv/Uf2xBfvO6W1FE1S4cdAmwl+Jd43Soa693DdZAWgtSopVvW1a7sj7ji1kgy04vHGjisEbNx0rEbnaSL1Y8y+2SYLu3PST9ma2Vq5M4BDwDxNXR272FPXyCW2Bj8vGxFIpcZb/8FTdzHJEvQTOr/aHe+/UNWlbW39I6CW7vQG727JAsAjFpN3Kh4yUNJQDcMBFTzzKjjkLZNU5IxRGuhGFpobM8Y99/ScwFXc9rQdAojYoQcWNmdsqD1bRtoXUD4LTqnUpJuO/uWRPVW4=
    on:
      tags: true
      branch: master
