name: Style

on: [pull_request]

jobs:
  lint_and_black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install tox
        run: pip install tox
      - name: Run style
        run: |
          tox -e linting
          tox -e formatting
