name: style

on: [pull_request]

jobs:
  lint_and_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install everviz with style dependencies
        run: |
          pip install ".[style]"
      - name: Run style check
        run: |
          ruff check
          ruff format --check
